### ISSUE TITLE
Should `openff.models` be a dependency?

### ISSUE THREAD

**Issue by SimonBoothroyd** [conda-forge/smirnoff-plugins-feedstock#12]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

Currently `openff.models` [is imported](https://github.com/openforcefield/smirnoff-plugins/blob/559503a6f1d0ab7e64a7b07dcb5eb0e46d512567/smirnoff_plugins/collections/nonbonded.py#L13) but not listed as a dependency. I'm guessing older versions of the toolkit / interchange used to have it as a dependency but maybe dropped this recently?

### Installed packages

```shell
smirnoff-plugins          2024.07.0          pyhd8ed1ab_0    conda-forge
openff-forcefields        2024.09.0          pyhff2d567_0    conda-forge
openff-interchange-base   0.4.0              pyhd8ed1ab_0    conda-forge
openff-toolkit-base       0.16.6             pyhd8ed1ab_0    conda-forge
```

### Environment info

```shell
active environment : smee
    active env location : /xxx/envs/smee
            shell level : 1
       user config file : /xxx/.condarc
 populated config files : /xxx/.condarc
                          /xxx/.condarc
          conda version : 23.11.0
    conda-build version : not installed
         python version : 3.10.13.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=m1
                          __conda=23.11.0=0
                          __osx=14.3=0
                          __unix=0=0
       base environment : /xxx  (writable)
      conda av data dir : /xxx/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /xxx/pkgs
                          /xxx/.conda/pkgs
       envs directories : /xxx/envs
                          /xxx/.conda/envs
               platform : osx-arm64
             user-agent : conda/23.11.0 requests/2.31.0 CPython/3.10.13 Darwin/23.3.0 OSX/14.3 solver/libmamba conda-libmamba-solver/23.12.0 libmambapy/1.5.5
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by mattwthompson** [comment]
Apologies for not making this more public

* Interchange 0.4 drops `openff-models` in favor of (updated versions of) vendored solutions of the same glue
  * The associated update is in the review pipeline (https://github.com/openforcefield/smirnoff-plugins/issues/75) and should be a quick merge + release + build once it gets some eyes to safeguard against my propensity for typos and gaffes
  * `openff-models` indeed should be removed from packaging in the next release (2024.10.0 ?)
* The released `smirnoff-plugins` only works with Interchange 0.3 - I think a temporary pin of it should patch things over in the mean time

**Comment by mattwthompson** [comment]
2024.10.0 is live and shouldn't need `openff-models`
